### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by ParasMore** [limdev212/LITRealty#1]
Hello i have seen you issue here

https://github.com/psieg/Lightpack/issues/458

i really want to learn and create this software on my own version 

please contact me on parasm12345@gmail.com

I hope i will get your mail soon thank you

**Comment by limdev212** [comment]
Hey there, I'm sorry but the instructions given in the issues are quite clear on what to do to get the build working. Other than that I would not be able to help. Just follow the instructions as given by zoomfg in the issues and wiki.

**Comment by ParasMore** [comment]
I am so sorry if i did anything wrong but i am new in this i really have no idea what to do i just want to know can i change whole software?

i just want to change some options please let me know if i can 

and how can i do it 

Prismatik Build Instructions for Windows
Prerequisites:
Qt SDK, you may need to set %QTDIR% (sysdm.cpl → Advanced → Environment Variables → New) to something like C:\Qt\x.xx.x\msvc_xxxx\.
Visual Studio, Windows SDK or Microsoft DirectX SDK
optional (if you want to create an installer) POSIX shell utilities MSYS for example.
optional any OpenSSL binaries to include them in the setup. If you just want to build, you can skip them in build-vars.prf (this will render the update check ineffective).
optional BASS and BASSWASAPI for the Sound Visualizer. You can skip them in build-vars.prf.
Build Process:
Go to <repo>/Software
Copy and edit build-vars.prf according to your machine
Optional: if locales changed: run update_locales.bat or ./update_locales.sh (slow on Windows)
Run scripts/win32/generate_sln.bat (from the Visual Studio Developer prompt / vcvarsall.bat)
Build Lightpack.sln with MSBuild / VisualStudio
Building an Installer:
Run scripts/win32/prepare_installer.sh. (This builds the autoupdater (UpdateElevate), needs the submodule checked out and currently works only with VS2015).
Build dist_windows/script.iss (64bit) or script32.iss (32bit) with ISCC (the InnoSetup compiler)


is this the way???

i tried and follow all the step but i dont know not got any thing....
